name: pyhanlp-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - openjdk
  - jpype1==0.7.0
  - python<3.9
  - pip:
      - sklearn
      - git+https://github.com/hankcs/pyhanlp.git@master